(ns tic-tac-toe.constant)

(def SPACE " ")
(def PLAYER-1-SYMBOL "X")
(def PLAYER-2-SYMBOL "O")
(def ENTER-FIRST-PLAYER-TEXT "Enter first player")
(def ENTER-SECOND-PLAYER-TEXT "Enter second player")
(def PLAYER-MOVE-MESSAGE "Enter your move (1 - 9)")
(def TURN "'s turn")
(def GREET-MESSAGE "Congratulations,")
(def WINNING-MESSAGE "has won!!!")
(def TOTAL-MOVE-COUNT 9)
(def COLUMN-SEPARATOR "|")
(def NEWLINE "\n")
(def ROW-SEPARATOR  "------------")